name: ZMediumToMarkdown
on:
  workflow_dispatch:
  schedule:
    - cron: "00 0 2 * *" # At 01:10 on day-of-month 15. (once a month)

jobs:
  ZMediumToMarkdown:
    runs-on: ubuntu-latest
    steps:
    - name: ZMediumToMarkdown Automatic Bot
      uses: ZhgChgLi/ZMediumToMarkdown@main
      with:
        command: '-u leventd'
